### ISSUE TITLE
square_in_app_payments App Crash on Android release mode 

### ISSUE THREAD

**Issue by jaiiidiii** [square/in-app-payments-flutter-plugin#185]
### Describe the issue

App is working fine on android debug mode and also in iOS but crashing on android release mode

** My Implementation **
  Future<void> onStartCardEntryFlow(String? appID) async {
    // this.amountPayable = amountPayable;
    await InAppPayments.setSquareApplicationId(appID ?? squareApplicationId);
    if (Platform.isIOS) {
      await _setIOSCardEntryTheme();
    }
    await InAppPayments.startCardEntryFlow(
        onCardNonceRequestSuccess: _onCardEntryCardNonceRequestSuccess,
        onCardEntryCancel: () {},
        collectPostalCode: false);
  }

**Environment (please complete the following information):**
<!--
  - platform: Android
  - OS and version: Android version 11
  - dev environment: MacOS
  - square_in_app_payments: ^1.7.3

junaidkhan@Junaids-MBP Inatote-Customer-Flutter % flutter doctor -v
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.3.1 21E258 darwin-x64, locale en-PK)
    • Flutter version 2.10.3 at /Users/junaidkhan/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (7 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/junaidkhan/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (2 available)
    • SM A025F (mobile) • R9YR30GJ5EJ • android-arm    • Android 11 (API 30)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 100.0.4896.88
    ! Error: Jaiidiii iPhone X is not connected. Xcode will continue when Jaiidiii iPhone X is connected. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
junaidkhan@Junaids-MBP Inatote-Customer-Flutter % 

https://user-images.githubusercontent.com/23140557/164053551-0d02f3c5-4c77-4e74-9579-8b4d4fc1c08e.mp4

**Comment by jaiiidiii** [comment]
Any update on this ??

**Comment by deepakrana0011** [comment]
@jaiiidiii have you get any solution for this . I am also facing the same issue

**Comment by jaiiidiii** [comment]
> @jaiiidiii have you get any solution for this . I am also facing the same issue

@deepakrana0011 Not yet :|

**Comment by deepakrana0011** [comment]
@jaiiidiii quick solution for this:
1. Upgrage the plugin to latest version 1.7.3
2. Remove this line android.enableJetifier=true from the gradle.properties
3. Add proguard-rules.pro file inisde app folder of android

**Comment by d3vtoolsmith** [comment]
> @jaiiidiii quick solution for this:
> 
> 1. Upgrage the plugin to latest version 1.7.3
> 2. Remove this line android.enableJetifier=true from the gradle.properties
> 3. Add proguard-rules.pro file inisde app folder of android

Sadly, this doesn't solve the issue. "Add Card" still hard crashes the whole app when in release mode on the Play Store (any track). This issue has been in this library for years, with hacky workarounds that stop working now and then.

**Comment by CharmisG** [comment]
Fixed please pull the latest code .

**Comment by David-GIC** [comment]
still error when build release

**Comment by David-GIC** [comment]
> Fixed please pull the latest code .


still error when build release

**Comment by ElAdrixHD** [comment]
This still happen when a credit card needs 3DS verification.

**Comment by josefKiefer** [comment]
@CharmisG this issue is still happening in ^1.7.5 while doing `InAppPayments.startCardEntryFlow` in Android release mode only
